<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.product.update.filler.product_filler' shared service.

return $this->services['prestashop.adapter.product.update.filler.product_filler'] = new \PrestaShop\PrestaShop\Adapter\Product\Update\Filler\ProductFiller(new RewindableGenerator(function () {
    yield 0 => ($this->services['prestashop.adapter.product.update.filler.basic_information_filler'] ?? $this->load('getPrestashop_Adapter_Product_Update_Filler_BasicInformationFillerService.php'));
    yield 1 => ($this->services['prestashop.adapter.product.update.filler.options_filler'] ?? ($this->services['prestashop.adapter.product.update.filler.options_filler'] = new \PrestaShop\PrestaShop\Adapter\Product\Update\Filler\OptionsFiller()));
    yield 2 => ($this->services['prestashop.adapter.product.update.filler.prices_filler'] ?? $this->load('getPrestashop_Adapter_Product_Update_Filler_PricesFillerService.php'));
    yield 3 => ($this->services['prestashop.adapter.product.update.filler.seo_filler'] ?? $this->load('getPrestashop_Adapter_Product_Update_Filler_SeoFillerService.php'));
    yield 4 => ($this->services['prestashop.adapter.product.update.filler.details_filler'] ?? ($this->services['prestashop.adapter.product.update.filler.details_filler'] = new \PrestaShop\PrestaShop\Adapter\Product\Update\Filler\DetailsFiller()));
    yield 5 => ($this->services['prestashop.adapter.product.update.filler.shipping_filler'] ?? ($this->services['prestashop.adapter.product.update.filler.shipping_filler'] = new \PrestaShop\PrestaShop\Adapter\Product\Update\Filler\ShippingFiller()));
    yield 6 => ($this->services['prestashop.adapter.product.update.filler.stock_information_filler'] ?? ($this->services['prestashop.adapter.product.update.filler.stock_information_filler'] = new \PrestaShop\PrestaShop\Adapter\Product\Update\Filler\StockInformationFiller()));
}, 7));
