<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.product.command_handler.update_product_handler' shared service.

return $this->services['prestashop.adapter.product.command_handler.update_product_handler'] = new \PrestaShop\PrestaShop\Adapter\Product\CommandHandler\UpdateProductHandler(($this->services['prestashop.adapter.product.update.filler.product_filler'] ?? $this->load('getPrestashop_Adapter_Product_Update_Filler_ProductFillerService.php')), ($this->services['prestashop.adapter.product.repository.product_multi_shop_repository'] ?? $this->load('getPrestashop_Adapter_Product_Repository_ProductMultiShopRepositoryService.php')), ($this->services['prestashop.adapter.product.update.product_indexation_updater'] ?? $this->load('getPrestashop_Adapter_Product_Update_ProductIndexationUpdaterService.php')), ($this->services['PrestaShop\\PrestaShop\\Adapter\\Product\\Repository\\ProductSupplierRepository'] ?? $this->load('getProductSupplierRepositoryService.php')));
