<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.category.name_builder.category_display_name_builder' shared service.

return $this->services['prestashop.core.category.name_builder.category_display_name_builder'] = new \PrestaShop\PrestaShop\Core\Category\NameBuilder\CategoryDisplayNameBuilder(($this->services['prestashop.adapter.category.repository.category_repository'] ?? $this->load('getPrestashop_Adapter_Category_Repository_CategoryRepositoryService.php')), ' > ');
