<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.category.query_handler.get_categories_tree_handler' shared service.

return $this->services['prestashop.adapter.category.query_handler.get_categories_tree_handler'] = new \PrestaShop\PrestaShop\Adapter\Category\QueryHandler\GetCategoriesTreeHandler(($this->services['prestashop.core.category.name_builder.category_display_name_builder'] ?? $this->load('getPrestashop_Core_Category_NameBuilder_CategoryDisplayNameBuilderService.php')), ($this->services['prestashop.adapter.context_state_manager'] ?? $this->load('getPrestashop_Adapter_ContextStateManagerService.php')), ($this->services['prestashop.adapter.shop.repository.shop_repository'] ?? ($this->services['prestashop.adapter.shop.repository.shop_repository'] = new \PrestaShop\PrestaShop\Adapter\Shop\Repository\ShopRepository())), ($this->services['prestashop.adapter.legacy.configuration'] ?? ($this->services['prestashop.adapter.legacy.configuration'] = new \PrestaShop\PrestaShop\Adapter\Configuration()))->get("PS_ROOT_CATEGORY"));
