<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.product.combination.update.combination_deleter' shared service.

return $this->services['prestashop.adapter.product.combination.update.combination_deleter'] = new \PrestaShop\PrestaShop\Adapter\Product\Combination\Update\CombinationDeleter(($this->services['prestashop.adapter.product.repository.product_multi_shop_repository'] ?? $this->load('getPrestashop_Adapter_Product_Repository_ProductMultiShopRepositoryService.php')), ($this->services['prestashop.adapter.product.combination.repository.combination_multi_shop_repository'] ?? $this->load('getPrestashop_Adapter_Product_Combination_Repository_CombinationMultiShopRepositoryService.php')), ($this->services['PrestaShop\\PrestaShop\\Adapter\\Product\\Combination\\Update\\DefaultCombinationUpdater'] ?? $this->load('getDefaultCombinationUpdaterService.php')));
