<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7AoTP9x\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7AoTP9x/appAppKernelProdContainer.php') {
    touch(__DIR__.'/Container7AoTP9x.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\Container7AoTP9x\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \Container7AoTP9x\appAppKernelProdContainer([
    'container.build_hash' => '7AoTP9x',
    'container.build_id' => 'c2b1b3de',
    'container.build_time' => 1670711753,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7AoTP9x');
