<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\DataHandler\BulkCombinationFormDataHandler' shared autowired service.

return $this->services['PrestaShop\\PrestaShop\\Core\\Form\\IdentifiableObject\\DataHandler\\BulkCombinationFormDataHandler'] = new \PrestaShop\PrestaShop\Core\Form\IdentifiableObject\DataHandler\BulkCombinationFormDataHandler(($this->services['prestashop.core.command_bus'] ?? $this->load('getPrestashop_Core_CommandBusService.php')), ($this->services['PrestaShop\\PrestaShop\\Core\\Form\\IdentifiableObject\\DataFormatter\\BulkCombinationFormDataFormatter'] ?? ($this->services['PrestaShop\\PrestaShop\\Core\\Form\\IdentifiableObject\\DataFormatter\\BulkCombinationFormDataFormatter'] = new \PrestaShop\PrestaShop\Core\Form\IdentifiableObject\DataFormatter\BulkCombinationFormDataFormatter())), ($this->services['PrestaShop\\PrestaShop\\Core\\Form\\IdentifiableObject\\CommandBuilder\\Product\\Combination\\CombinationCommandsBuilder'] ?? $this->load('getCombinationCommandsBuilderService.php')));
