<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.product.command.update_combination_stock_handler' shared service.

return $this->services['prestashop.adapter.product.command.update_combination_stock_handler'] = new \PrestaShop\PrestaShop\Adapter\Product\Combination\CommandHandler\UpdateCombinationStockHandler(($this->services['PrestaShop\\PrestaShop\\Adapter\\Product\\Combination\\Update\\CombinationStockUpdater'] ?? $this->load('getCombinationStockUpdaterService.php')), ($this->services['PrestaShop\\PrestaShop\\Adapter\\Product\\Stock\\Repository\\MovementReasonRepository'] ?? $this->load('getMovementReasonRepositoryService.php')), ($this->services['PrestaShop\\PrestaShop\\Adapter\\Product\\Stock\\Repository\\StockAvailableRepository'] ?? $this->load('getStockAvailableRepositoryService.php')));
