<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.product.update.filler.stock_information_filler' shared service.

return $this->services['prestashop.adapter.product.update.filler.stock_information_filler'] = new \PrestaShop\PrestaShop\Adapter\Product\Update\Filler\StockInformationFiller();
