<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShop\PrestaShop\Adapter\Product\Repository\ProductSupplierRepository' shared service.

return $this->services['PrestaShop\\PrestaShop\\Adapter\\Product\\Repository\\ProductSupplierRepository'] = new \PrestaShop\PrestaShop\Adapter\Product\Repository\ProductSupplierRepository(($this->services['doctrine.dbal.default_connection'] ?? $this->getDoctrine_Dbal_DefaultConnectionService()), 'ps_', ($this->services['prestashop.adapter.product.validate.product_supplier_validator'] ?? $this->load('getPrestashop_Adapter_Product_Validate_ProductSupplierValidatorService.php')));
