<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.product.image.command_handler.set_product_images_for_all_shop_handler' shared service.

return $this->services['prestashop.adapter.product.image.command_handler.set_product_images_for_all_shop_handler'] = new \PrestaShop\PrestaShop\Adapter\Product\Image\CommandHandler\SetProductImagesForAllShopHandler(($this->services['prestashop.adapter.product.image.repository.product_image_repository'] ?? $this->load('getPrestashop_Adapter_Product_Image_Repository_ProductImageRepositoryService.php')), ($this->services['prestashop.adapter.product.repository.product_multi_shop_repository'] ?? $this->load('getPrestashop_Adapter_Product_Repository_ProductMultiShopRepositoryService.php')), ($this->services['prestashop.adapter.product.image.repository.product_image_multishop_repository'] ?? $this->load('getPrestashop_Adapter_Product_Image_Repository_ProductImageMultishopRepositoryService.php')));
