<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.product.combination.command_handler.update_combination_suppliers_handler' shared service.

return $this->services['prestashop.adapter.product.combination.command_handler.update_combination_suppliers_handler'] = new \PrestaShop\PrestaShop\Adapter\Product\Combination\CommandHandler\UpdateCombinationSuppliersHandler(($this->services['PrestaShop\\PrestaShop\\Adapter\\Product\\Combination\\Repository\\CombinationRepository'] ?? $this->load('getCombinationRepositoryService.php')), ($this->services['PrestaShop\\PrestaShop\\Adapter\\Product\\Repository\\ProductSupplierRepository'] ?? $this->load('getProductSupplierRepositoryService.php')), ($this->services['prestashop.adapter.product.update.product_supplier_updater'] ?? $this->load('getPrestashop_Adapter_Product_Update_ProductSupplierUpdaterService.php')));
