<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerY6CZZFh\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerY6CZZFh/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerY6CZZFh.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerY6CZZFh\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \ContainerY6CZZFh\appAppKernelDevDebugContainer([
    'container.build_hash' => 'Y6CZZFh',
    'container.build_id' => 'c4a19cf6',
    'container.build_time' => 1670763922,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerY6CZZFh');
